// TPC BUILD - Build Exporter & Shareable URL Generator

import { COMPONENTS, HARDWARE_CATEGORIES } from '../data/components.js';

export function encodeBuildToHash(build) {
  try {
    const compact = {};
    for (const [k, v] of Object.entries(build)) {
      if (v) compact[k] = v;
    }
    const jsonStr = JSON.stringify(compact);
    return '#' + btoa(encodeURIComponent(jsonStr));
  } catch (e) {
    console.error('Failed to encode build hash', e);
    return '';
  }
}

export function decodeBuildFromHash(hash) {
  if (!hash || hash.length < 2) return null;
  try {
    const raw = hash.startsWith('#') ? hash.substring(1) : hash;
    const jsonStr = decodeURIComponent(atob(raw));
    return JSON.parse(jsonStr);
  } catch (e) {
    console.error('Failed to decode build hash', e);
    return null;
  }
}

export function generateRedditMarkdown(build, totalCost, totalTdp) {
  let md = `**TPC BUILD: Build and test your rig virtually**

`;
  md += `| Component | Part Name | Price | Buying Links |
`;
  md += `| :--- | :--- | :--- | :--- |
`;

  for (const cat of HARDWARE_CATEGORIES) {
    const partId = build[cat.id];
    if (partId) {
      const part = (COMPONENTS[cat.id] || []).find(p => p.id === partId);
      if (part) {
        md += `| **${cat.name}** | ${part.name} | **$${part.price}** | [Amazon](${part.links.amazon}) ? [Newegg](${part.links.newegg}) |
`;
      }
    } else {
      md += `| **${cat.name}** | *None Selected* | - | - |
`;
    }
  }

  md += `
**Total Build Cost:** **$${totalCost} USD**
`;
  md += `**Estimated Peak Draw:** ~${totalTdp}W
`;
  md += `*Generated by TPC BUILD (Virtual PC Builder & Real-Time FPS Engine)*
`;

  return md;
}
